org: rafaelram
service: generate-service

package:
  individually: true

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::582232142172:role/LabRole
  environment:
    TOKENS_TABLE: h_tokens_access
    DIAGRAMS_TABLE: h_diagrams
    BUCKET: diagramas-hackacloud-${self:provider.stage}

layers:
  extraLibs:
    path: layers/extraLibs
    compatibleRuntimes:
      - python3.13
    package:
      exclude:
        - nodejs/node_modules/**/*.{md,markdown}
        - nodejs/node_modules/**/test/**
        - nodejs/node_modules/**/__tests__/**
        - nodejs/node_modules/**/docs/**
        - nodejs/node_modules/**/examples/**
        - nodejs/node_modules/**/scripts/**
        - nodejs/node_modules/**/CHANGELOG*.*
        - python/**/*

functions:
  preview:
    handler: handler_preview.lambda_handler
    package:
      include:
        - handler_preview.py
        - parser_json.py
        - renderer.py
    layers:
      - { Ref: ExtraLibsLambdaLayer }
    events:
      - http:
          path: /generate/preview
          method: post
          cors: true

  save:
    handler: handler_save.lambda_handler
    package:
      include:
        - handler_save.py
        - parser_json.py
        - renderer.py
    layers:
      - { Ref: ExtraLibsLambdaLayer }
    events:
      - http:
          path: /generate/save
          method: post
          cors: true

  save-frontend:
    handler: handler_save_frontend.lambda_handler
    package:
      include:
        - handler_save_frontend.py
        - auth_utils.py
    events:
      - http:
          path: /generate/save-frontend
          method: post
          cors: true

resources:
  Resources:
    # Tabla de Digramas
    DiagramsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: h_diagrams
        AttributeDefinitions:
          - AttributeName: owner_id
            AttributeType: S
          - AttributeName: diagram_id
            AttributeType: S
        KeySchema:
          - AttributeName: owner_id
            KeyType: HASH
          - AttributeName: diagram_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST    
    # Bucket de Diagramas
    DiagramsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: diagramas-hackacloud-${self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        AccessControl: PublicRead
